TOA_PATH_LEVEL_NPCS = {
    "Zebak", "Kephri", "Ba-Ba", "Akkha"
}

SPEC_REGEN_PER_TICK = 0.2  # 10% per 30 sec or 0.2% per tick
SPEC_REGEN_TICKS = 50
SPEC_REGEN_AMOUNT = 10
MAX_SPECIAL_ATTACK = 100

TICK_LENGTH = 0.6

MAX_X_TICKS_LABEL = 30
