service: osrs-dmg-sim-go
frameworkVersion: '>=4.1'
configValidationMode: error

provider:
  name: aws
  runtime: provided.al2023
  region: eu-central-1
  stage: ${opt:stage}

custom:
  corsConfig:
    origin: 'https://maurits825.github.io'
    headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
    allowCredentials: false
  
functions:
  api:
   handler: bootstrap
   timeout: 10
   
   events:
    - http:
        path: /status
        method: GET
    - http:
        path: /lookup-highscore
        method: GET
    - http:
        path: /run-dps-calc
        method: POST
        cors: ${self:custom.corsConfig}
    - http:
        path: /run-bis-calc
        method: POST
        cors: ${self:custom.corsConfig}
    - http:
        path: /wiki-dps-shortlink
        method: POST
        cors: ${self:custom.corsConfig}
    
package:
  patterns:
    - '!*/**'
    - bootstrap
