package dpscalc

var standardSpells = []string{
	"Wind Strike",
	"Water Strike",
	"Earth Strike",
	"Fire Strike",
	"Wind Bolt",
	"Water Bolt",
	"Earth Bolt",
	"Fire Bolt",
	"Wind Blast",
	"Water Blast",
	"Crumble Undead",
	"Earth Blast",
	"Fire Blast",
	"Wind Wave",
	"Water Wave",
	"Earth Wave",
	"Saradomin Strike",
	"Claws of Guthix",
	"Flames of Zamorak",
	"Fire Wave",
	"Wind Surge",
	"Water Surge",
	"Earth Surge",
	"Fire Surge",
}

var ancientSpells = []string{
	"Smoke Rush",
	"Shadow Rush",
	"Blood Rush",
	"Ice Rush",
	"Smoke Burst",
	"Shadow Burst",
	"Blood Burst",
	"Ice Burst",
	"Smoke Blitz",
	"Shadow Blitz",
	"Blood Blitz",
	"Ice Blitz",
	"Smoke Barrage",
	"Shadow Barrage",
	"Blood Barrage",
	"Ice Barrage",
}
