name: osrs-dmg-sim-benchmark
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  benchmark:
    name: Benchmark Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/osrs-dmg-sim

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      # Run benchmark with `go test -bench` and stores the output to a file
      - name: Run benchmark
        run: go test -v ./... -bench . -run=xxx | tee output.txt
      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          # What benchmark tool the output.txt came from
          tool: 'go'
          # Where the output from the benchmark tool is stored
          output-file-path: backend/osrs-dmg-sim/output.txt
          # Where the previous data file is stored
          external-data-json-path: ./cache/benchmark-data.json
          summary-always: true
