name: osrs-dmg-sim-deploy

on:
  workflow_run:
    workflows: [osrs-dmg-sim-test]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    name: Deploy to AWS
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/osrs-dmg-sim

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: ./backend/osrs-dmg-sim/go.sum

      - name: Install dependencies
        run: |
          go get .
          npm install -g serverless@latest

      - name: Configure AWS Credentials
        run: |
          aws configure set region eu-central-1 --profile default
          aws configure set output json --profile default
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile default
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default

      - name: Build and Deploy
        run: |
          make deploy
