name: web-app-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  changes:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    
    steps:
    - name: Check out
      uses: actions/checkout@v4
      
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          frontend:
            - 'frontend/**'

  test:
    name: Test
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/osrs-damage-sim

    steps:
      - name: Check out
        uses: actions/checkout@v3
        
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: ./frontend/osrs-damage-sim/node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nodemodules-

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm install --legacy-peer-deps
        
      - name: Lint
        run: npm run lint -- --max-warnings=0

      - name: Unit test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless
